env = Environment (CXX = 'ccache g++')
env = Environment (CC  = 'ccache gcc')

Program ('ccgs',
        ['ccgs.cpp',
		 'ccgs_configure.cpp',
		 'ccgs_event_loop.cpp',
		 'ccgs_recv_task.cpp',
		 'ccgs_singleton.cpp',
		 'ccgs_db_connection.cpp',
		 'ccgs_manager.cpp',
		 'ccgs_send_task.cpp',
		 'ccgs_thread_pool.cpp',
         'ccgs_memcached.cpp',
		 'ccgs_utils.c'],

        LIBS    = ['memcached','pthread','ev','glog','mysqlcppconn','lua5.2'],
        LIBPATH = ['/usr/lib','/usr/local/lib'],
        CCFLAGS = ['-Wall','-Werror','-g'],
        CPPPATH = ['-I.','-I./includes']
        )
